# General Jekyll Config
highlighter: rouge
url: https://blog.binarynonsense.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
baseurl: https://blog.binarynonsense.com
excerpt_separator: "<!-- more -->"
timezone: Europe/Madrid

# Permalinks
permalink: /:year/:month/:day/:title/
