# General Jekyll Config
highlighter: pygments
url: http://blog.binarynonsense.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
baseurl: http://blog.binarynonsense.com
excerpt_separator: "<!-- more -->"

# Permalinks
permalink:        /:year/:month/:day/:title/
relative_permalinks: true